services:
  react-support-app-dev:
    image: 043207749006.dkr.ecr.us-east-1.amazonaws.com/varunerp/react-support-app:dev
    container_name: react-support-app-dev
    restart: unless-stopped
    ports:
      - "8083:80"
    mem_limit: 256m
    cpus: 0.25
    networks:
      - react-support-app-dev-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 15s
      timeout: 3s
      retries: 3
    logging:
      driver: json-file
      options:
        tag: "react-support-app-dev"
        max-size: "10m"
        max-file: "3"

networks:
  react-support-app-dev-net:
    driver: bridge
